### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [dauwhe/epub-zero#19]
Amazing demo. Great start. Etc. 😁 

One thing it lacks currently is a `LICENSE` file or other declaration of intended licensing.

At present, it's technically "All Rights Reserved" (at least in most countries...).

If you need help, checkout http://choosealicense.org/ (or we can chat!). 😄

**Comment by dauwhe** [comment]
This particular project was moved to github.com/dauwhe/acme-labs and now has an MIT license! Thanks so much for bringing this up!
